# lightning.pytorch==2.1.2
seed_everything: 102
data:
  data_dir: /opt/dlami/nvme
  size: 64
  metadata_path: configs/metadata.yaml
  platforms:
    - landsat-c2l1
    - landsat-c2l2-sr
    - linz
    - naip
    - sentinel-1-rtc
    - sentinel-2-l2a
  batch_size: 20
  num_workers: 16
model:
  model_size: base
  mask_ratio: 0.75
  norm_pix_loss: True
  patch_size: 8
  shuffle: True
  metadata_path: configs/metadata.yaml
  teacher: vit_base_patch16_224.dino
  lr: 1e-5
  wd: 0.05
  b1: 0.9
  b2: 0.95
  embeddings_level: mean
  ckpt: checkpoints/mae_v0.5.3_epoch-33_val-loss-0.3059.ckpt
trainer:
  accelerator: auto
  strategy: ddp
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  log_every_n_steps: 10
  max_epochs: 200
  accumulate_grad_batches: 1
  default_root_dir: s3://clay-model-ckpt/v0.6.0/
  # val_check_interval: 0.5
  fast_dev_run: False
  limit_train_batches: 0.15
  limit_val_batches: 0.15
  num_sanity_val_steps: 0
  use_distributed_sampler: False
  # logger:
  #   - class_path: lightning.pytorch.loggers.CSVLogger
  #     init_args:
  #       save_dir: log_dir
  #       name: testv0.6.0
  logger:
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        entity: developmentseed
        project: clay
        log_model: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: s3://clay-model-ckpt/v0.6.0/
        auto_insert_metric_name: False
        filename: mae_v0.6.0_epoch-{epoch:02d}_val-loss-{val/loss:.4f}
        monitor: val/loss
        mode: min
        save_last: True
        save_top_k: 2
        save_weights_only: False
        verbose: True
    # - class_path: src.callbacks.ProgressiveResize
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: src.callbacks_wandb.LogIntermediatePredictions
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
ckpt_path: null
