s2:
  band_order:
    - blue
    - green
    - red
    - rededge1
    - rededge2
    - rededge3
    - nir
    - nir08
    - swir16
    - swir22
  rgb_indices:
    - 2
    - 1
    - 0
  gsd: 20
  bands:
    mean:
      blue: 550
      green: 770
      red: 840
      rededge1: 1240
      rededge2: 2000
      rededge3: 2360
      nir: 2480
      nir08: 2600
      swir16: 2000
      swir22: 1230
    std:
      blue: 780
      green: 780
      red: 840
      rededge1: 1240
      rededge2: 2050
      rededge3: 2360
      nir: 2500
      nir08: 2630
      swir16: 2000
      swir22: 1230
    wavelength:
      blue: 0.4905
      green: 0.5605
      red: 0.665
      rededge1: 0.7055
      rededge2: 0.7405
      rededge3: 0.783
      nir: 0.8425
      nir08: 0.865
      swir16: 1.61
      swir22: 2.19
naip:
  band_order:
    - red
    - green
    - blue
    - nir
  rgb_indices:
    - 0
    - 1
    - 2
  gsd: 1.0
  bands:
    mean:
      red: 120
      green: 110
      blue: 100
      nir: 130
    std:
      red: 40
      green: 30
      blue: 20
      nir: 50
    wavelength:
      red: 0.66
      green: 0.53
      blue: 0.48
      nir: 0.86
linz:
  band_order:
    - blue
    - green
    - red
    - nir
  rgb_indices:
    - 2
    - 1
    - 0
  gsd: 0.1
  bands:
    mean:
      blue: 100
      green: 100
      red: 100
    std:
      blue: 25
      green: 25
      red: 25
    wavelength:
      blue: 0.48
      green: 0.53
      red: 0.66
